openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  $ref: ../external-docs.yaml
servers:
  - $ref: ../server-default.yaml
tags:
  - name: Copilot - Anomalies
    description: 'The Copilot Anomalies API'
paths:
  /copilot/anomalies/locations:
    $ref: paths/copilot_anomalies_locations.yaml
  /copilot/anomalies/devices-by-location:
    $ref: paths/copilot_anomalies_devices-by-location.yaml
  /copilot/anomalies/poeflapping/stats:
    $ref: paths/copilot_anomalies_poeflapping_stats.yaml
components:
  securitySchemes:
    $ref: ../common/components/securitySchemes/index.yaml