openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  $ref: ../external-docs.yaml
servers:
  - $ref: ../server-default.yaml
tags:
  - name: Copilot - Anomalies
    description: 'The Copilot Anomalies API'
paths:
  /copilot/anomaly-locations:
    $ref: paths/copilot_anomaly_locations.yaml
  /copilot/anomaly-devices:
    $ref: paths/copilot_anomaly_devices.yaml
  /copilot/anomaly-device/stats:
    $ref: paths/copilot_anomaly_device_stats.yaml
components:
  securitySchemes:
    $ref: ../common/components/securitySchemes/index.yaml