openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  $ref: ../external-docs.yaml
servers:
  - $ref: ../server-default.yaml
tags:
  - name: Copilot
    description: 'Wired Connectivity Experience'
paths:
  /copilot/connectivity/wireless/experience:
    $ref: paths/copilot_wireless_experience.yaml
  /copilot/connectivity/wireless/quality-index:
    $ref: paths/copilot_wireless_quality_index.yaml
  /copilot/connectivity/wireless/time-to-connect:
    $ref: paths/copilot_wireless_time_to_connect.yaml
  /copilot/connectivity/wireless/performance:
    $ref: paths/copilot_wireless_performance.yaml
  /copilot/connectivity/wireless/events:
    $ref: paths/copilot_wireless_events.yaml
  /copilot/connectivity/wired/experience:
    $ref: paths/copilot_wired_experience.yaml
  /copilot/connectivity/wired/quality-index:
    $ref: paths/copilot_wired_quality_index.yaml
  /copilot/connectivity/wired/hardware:
    $ref: paths/copilot_wired_hardware.yaml
  /copilot/connectivity/wired/events:
    $ref: paths/copilot_wired_events.yaml
components:
  securitySchemes:
    $ref: ../common/components/securitySchemes/index.yaml