openapi: 3.0.3
info:
  title:
    $ref: ../info-title
  description:
    $ref: ../info-description.md
  termsOfService:
    $ref: ../info-termOfService
  contact:
    $ref: ../info-contact.yaml
  license:
    $ref: ../info-license.yaml
  version:
    $ref: ../info-version
externalDocs:
  $ref: ../external-docs.yaml
servers:
  - $ref: ../server-default.yaml
tags:
  - name: Authorization
    description: API token and permissions
paths:
  /auth/apitoken:
    $ref: paths/auth_apitoken.yaml
  /auth/apitoken/info:
    $ref: paths/auth_apitoken_info.yaml
  /auth/apitoken/validation:
    $ref: paths/auth_apitoken_validation.yaml
  /auth/permissions:
    $ref: paths/auth_permissions.yaml
  /auth/permissions/:check:
    $ref: paths/auth_permissions_:check.yaml
components:
  securitySchemes:
    $ref: ../common/components/securitySchemes/index.yaml
